// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/paloaltonetworks/pulumi-prismasdwan/sdk/go/prismasdwan/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The file path to the JSON file with auth creds for SCM.
func GetAuthFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:authFile")
}

// The URL to send auth credentials to which will return a JWT. Default:
// `https://auth.apps.paloaltonetworks.com/auth/v1/oauth2/access_token`. Environment variable: `SCM_AUTH_URL`. JSON config
// file variable: `authUrl`.
func GetAuthUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:authUrl")
}

// The client ID for the connection. Environment variable: `SCM_CLIENT_ID`. JSON config file variable: `clientId`.
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:clientId")
}

// The client secret for the connection. Environment variable: `SCM_CLIENT_SECRET`. JSON config file variable:
// `clientSecret`.
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:clientSecret")
}

// The hostname of Strata Cloud Manager API. Default: `pa-us01.api.prismaaccess.com`. Environment variable: `SCM_HOST`.
// JSON config file variable: `host`.
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:host")
}

// The logging level of the provider and the underlying communication. Default: `quiet`. Environment variable:
// `SCM_LOGGING`. JSON config file variable: `logging`.
func GetLogging(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:logging")
}

// The port number for API operations, if non-standard for the given protocol. Environment variable: `SCM_PORT`. JSON
// config file variable: `port`.
func GetPort(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "prismasdwan:port")
}

// The protocol (https or http). Default: `https`. Environment variable: `SCM_PROTOCOL`. JSON config file variable:
// `protocol`.
func GetProtocol(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:protocol")
}

// The client scope. Environment variable: `SCM_SCOPE`. JSON config file variable: `scope`.
func GetScope(ctx *pulumi.Context) string {
	return config.Get(ctx, "prismasdwan:scope")
}
