// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prismasdwan
{
    public static class GetSite
    {
        /// <summary>
        /// Retrieves the JSON pull-site info for a given site.  This can then be updated and sebsequently fed into the prismasdwan.Site resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prismasdwan = Pulumi.Prismasdwan;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var site1 = Prismasdwan.GetSite.Invoke(new()
        ///     {
        ///         SiteName = "Site1",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetSiteResult> InvokeAsync(GetSiteArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSiteResult>("prismasdwan:index/getSite:getSite", args ?? new GetSiteArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves the JSON pull-site info for a given site.  This can then be updated and sebsequently fed into the prismasdwan.Site resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prismasdwan = Pulumi.Prismasdwan;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var site1 = Prismasdwan.GetSite.Invoke(new()
        ///     {
        ///         SiteName = "Site1",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetSiteResult> Invoke(GetSiteInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSiteResult>("prismasdwan:index/getSite:getSite", args ?? new GetSiteInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSiteArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The site whose config should be retrieved.
        /// </summary>
        [Input("siteName", required: true)]
        public string SiteName { get; set; } = null!;

        public GetSiteArgs()
        {
        }
        public static new GetSiteArgs Empty => new GetSiteArgs();
    }

    public sealed class GetSiteInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The site whose config should be retrieved.
        /// </summary>
        [Input("siteName", required: true)]
        public Input<string> SiteName { get; set; } = null!;

        public GetSiteInvokeArgs()
        {
        }
        public static new GetSiteInvokeArgs Empty => new GetSiteInvokeArgs();
    }


    [OutputType]
    public sealed class GetSiteResult
    {
        /// <summary>
        /// The site config.
        /// </summary>
        public readonly string Config;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The site whose config should be retrieved.
        /// </summary>
        public readonly string SiteName;

        [OutputConstructor]
        private GetSiteResult(
            string config,

            string id,

            string siteName)
        {
            Config = config;
            Id = id;
            SiteName = siteName;
        }
    }
}
