// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.prismasdwan;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.prismasdwan.SiteArgs;
import com.pulumi.prismasdwan.Utilities;
import com.pulumi.prismasdwan.inputs.SiteState;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manages a Prisma SD-WAN site.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.prismasdwan.Site;
 * import com.pulumi.prismasdwan.SiteArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new Site("example", SiteArgs.builder()
 *             .config("/Users/jdoe/sdwan_configs/site1.yaml")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="prismasdwan:index/site:Site")
public class Site extends com.pulumi.resources.CustomResource {
    /**
     * The filesystem path of the site&#39;s JSON config.
     * 
     */
    @Export(name="config", refs={String.class}, tree="[0]")
    private Output<String> config;

    /**
     * @return The filesystem path of the site&#39;s JSON config.
     * 
     */
    public Output<String> config() {
        return this.config;
    }
    /**
     * This will be set to false if the site config deployed does not match the given config file.
     * 
     */
    @Export(name="isDeployed", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isDeployed;

    /**
     * @return This will be set to false if the site config deployed does not match the given config file.
     * 
     */
    public Output<Boolean> isDeployed() {
        return this.isDeployed;
    }
    @Export(name="tfid", refs={String.class}, tree="[0]")
    private Output<String> tfid;

    public Output<String> tfid() {
        return this.tfid;
    }
    /**
     * Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
     * 
     */
    @Export(name="timeout", refs={String.class}, tree="[0]")
    private Output<String> timeout;

    /**
     * @return Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
     * 
     */
    public Output<String> timeout() {
        return this.timeout;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Site(String name) {
        this(name, SiteArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Site(String name, SiteArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Site(String name, SiteArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("prismasdwan:index/site:Site", name, args == null ? SiteArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Site(String name, Output<String> id, @Nullable SiteState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("prismasdwan:index/site:Site", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Site get(String name, Output<String> id, @Nullable SiteState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Site(name, id, state, options);
    }
}
