// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.prismasdwan;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SiteArgs extends com.pulumi.resources.ResourceArgs {

    public static final SiteArgs Empty = new SiteArgs();

    /**
     * The filesystem path of the site&#39;s JSON config.
     * 
     */
    @Import(name="config", required=true)
    private Output<String> config;

    /**
     * @return The filesystem path of the site&#39;s JSON config.
     * 
     */
    public Output<String> config() {
        return this.config;
    }

    /**
     * This will be set to false if the site config deployed does not match the given config file.
     * 
     */
    @Import(name="isDeployed")
    private @Nullable Output<Boolean> isDeployed;

    /**
     * @return This will be set to false if the site config deployed does not match the given config file.
     * 
     */
    public Optional<Output<Boolean>> isDeployed() {
        return Optional.ofNullable(this.isDeployed);
    }

    /**
     * Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
     * 
     */
    @Import(name="timeout")
    private @Nullable Output<String> timeout;

    /**
     * @return Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
     * 
     */
    public Optional<Output<String>> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    private SiteArgs() {}

    private SiteArgs(SiteArgs $) {
        this.config = $.config;
        this.isDeployed = $.isDeployed;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SiteArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SiteArgs $;

        public Builder() {
            $ = new SiteArgs();
        }

        public Builder(SiteArgs defaults) {
            $ = new SiteArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param config The filesystem path of the site&#39;s JSON config.
         * 
         * @return builder
         * 
         */
        public Builder config(Output<String> config) {
            $.config = config;
            return this;
        }

        /**
         * @param config The filesystem path of the site&#39;s JSON config.
         * 
         * @return builder
         * 
         */
        public Builder config(String config) {
            return config(Output.of(config));
        }

        /**
         * @param isDeployed This will be set to false if the site config deployed does not match the given config file.
         * 
         * @return builder
         * 
         */
        public Builder isDeployed(@Nullable Output<Boolean> isDeployed) {
            $.isDeployed = isDeployed;
            return this;
        }

        /**
         * @param isDeployed This will be set to false if the site config deployed does not match the given config file.
         * 
         * @return builder
         * 
         */
        public Builder isDeployed(Boolean isDeployed) {
            return isDeployed(Output.of(isDeployed));
        }

        /**
         * @param timeout Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
         * 
         * @return builder
         * 
         */
        public Builder timeout(@Nullable Output<String> timeout) {
            $.timeout = timeout;
            return this;
        }

        /**
         * @param timeout Timeouts for this resource&#39;s operations. A custom timeout is a string that has a number and a units suffix, such as 30s or 1h1m1s. Valid units are &#34;h&#34;, &#34;m&#34;, or &#34;s&#34;. Note that changes to custom timeouts only take effect during resource creation or update. Default: 30m.
         * 
         * @return builder
         * 
         */
        public Builder timeout(String timeout) {
            return timeout(Output.of(timeout));
        }

        public SiteArgs build() {
            if ($.config == null) {
                throw new MissingRequiredPropertyException("SiteArgs", "config");
            }
            return $;
        }
    }

}
