// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package prismasdwan

import (
	"context"
	"reflect"

	"github.com/paloaltonetworks/pulumi-prismasdwan/sdk/go/prismasdwan/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves the JSON pull-site info for a given site.  This can then be updated and sebsequently fed into the Site resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/paloaltonetworks/pulumi-prismasdwan/sdk/go/prismasdwan"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := prismasdwan.LookupSite(ctx, &prismasdwan.LookupSiteArgs{
//				SiteName: "Site1",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSite(ctx *pulumi.Context, args *LookupSiteArgs, opts ...pulumi.InvokeOption) (*LookupSiteResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSiteResult
	err := ctx.Invoke("prismasdwan:index/getSite:getSite", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSite.
type LookupSiteArgs struct {
	// The site whose config should be retrieved.
	SiteName string `pulumi:"siteName"`
}

// A collection of values returned by getSite.
type LookupSiteResult struct {
	// The site config.
	Config string `pulumi:"config"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The site whose config should be retrieved.
	SiteName string `pulumi:"siteName"`
}

func LookupSiteOutput(ctx *pulumi.Context, args LookupSiteOutputArgs, opts ...pulumi.InvokeOption) LookupSiteResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSiteResult, error) {
			args := v.(LookupSiteArgs)
			r, err := LookupSite(ctx, &args, opts...)
			var s LookupSiteResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSiteResultOutput)
}

// A collection of arguments for invoking getSite.
type LookupSiteOutputArgs struct {
	// The site whose config should be retrieved.
	SiteName pulumi.StringInput `pulumi:"siteName"`
}

func (LookupSiteOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSiteArgs)(nil)).Elem()
}

// A collection of values returned by getSite.
type LookupSiteResultOutput struct{ *pulumi.OutputState }

func (LookupSiteResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSiteResult)(nil)).Elem()
}

func (o LookupSiteResultOutput) ToLookupSiteResultOutput() LookupSiteResultOutput {
	return o
}

func (o LookupSiteResultOutput) ToLookupSiteResultOutputWithContext(ctx context.Context) LookupSiteResultOutput {
	return o
}

// The site config.
func (o LookupSiteResultOutput) Config() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSiteResult) string { return v.Config }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSiteResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSiteResult) string { return v.Id }).(pulumi.StringOutput)
}

// The site whose config should be retrieved.
func (o LookupSiteResultOutput) SiteName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSiteResult) string { return v.SiteName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSiteResultOutput{})
}
