// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.prismasdwan.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSitePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSitePlainArgs Empty = new GetSitePlainArgs();

    /**
     * The site whose config should be retrieved.
     * 
     */
    @Import(name="siteName", required=true)
    private String siteName;

    /**
     * @return The site whose config should be retrieved.
     * 
     */
    public String siteName() {
        return this.siteName;
    }

    private GetSitePlainArgs() {}

    private GetSitePlainArgs(GetSitePlainArgs $) {
        this.siteName = $.siteName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSitePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSitePlainArgs $;

        public Builder() {
            $ = new GetSitePlainArgs();
        }

        public Builder(GetSitePlainArgs defaults) {
            $ = new GetSitePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param siteName The site whose config should be retrieved.
         * 
         * @return builder
         * 
         */
        public Builder siteName(String siteName) {
            $.siteName = siteName;
            return this;
        }

        public GetSitePlainArgs build() {
            if ($.siteName == null) {
                throw new MissingRequiredPropertyException("GetSitePlainArgs", "siteName");
            }
            return $;
        }
    }

}
