// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.prismasdwan.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSiteArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSiteArgs Empty = new GetSiteArgs();

    /**
     * The site whose config should be retrieved.
     * 
     */
    @Import(name="siteName", required=true)
    private Output<String> siteName;

    /**
     * @return The site whose config should be retrieved.
     * 
     */
    public Output<String> siteName() {
        return this.siteName;
    }

    private GetSiteArgs() {}

    private GetSiteArgs(GetSiteArgs $) {
        this.siteName = $.siteName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSiteArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSiteArgs $;

        public Builder() {
            $ = new GetSiteArgs();
        }

        public Builder(GetSiteArgs defaults) {
            $ = new GetSiteArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param siteName The site whose config should be retrieved.
         * 
         * @return builder
         * 
         */
        public Builder siteName(Output<String> siteName) {
            $.siteName = siteName;
            return this;
        }

        /**
         * @param siteName The site whose config should be retrieved.
         * 
         * @return builder
         * 
         */
        public Builder siteName(String siteName) {
            return siteName(Output.of(siteName));
        }

        public GetSiteArgs build() {
            if ($.siteName == null) {
                throw new MissingRequiredPropertyException("GetSiteArgs", "siteName");
            }
            return $;
        }
    }

}
