// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.prismasdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSiteResult {
    /**
     * @return The site config.
     * 
     */
    private String config;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The site whose config should be retrieved.
     * 
     */
    private String siteName;

    private GetSiteResult() {}
    /**
     * @return The site config.
     * 
     */
    public String config() {
        return this.config;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The site whose config should be retrieved.
     * 
     */
    public String siteName() {
        return this.siteName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSiteResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String config;
        private String id;
        private String siteName;
        public Builder() {}
        public Builder(GetSiteResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.id = defaults.id;
    	      this.siteName = defaults.siteName;
        }

        @CustomType.Setter
        public Builder config(String config) {
            if (config == null) {
              throw new MissingRequiredPropertyException("GetSiteResult", "config");
            }
            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSiteResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder siteName(String siteName) {
            if (siteName == null) {
              throw new MissingRequiredPropertyException("GetSiteResult", "siteName");
            }
            this.siteName = siteName;
            return this;
        }
        public GetSiteResult build() {
            final var _resultValue = new GetSiteResult();
            _resultValue.config = config;
            _resultValue.id = id;
            _resultValue.siteName = siteName;
            return _resultValue;
        }
    }
}
