// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves the JSON pull-site info for a given site.  This can then be updated and sebsequently fed into the prismasdwan.Site resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prismasdwan from "@pulumi/prismasdwan";
 *
 * const site1 = prismasdwan.getSite({
 *     siteName: "Site1",
 * });
 * ```
 */
export function getSite(args: GetSiteArgs, opts?: pulumi.InvokeOptions): Promise<GetSiteResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prismasdwan:index/getSite:getSite", {
        "siteName": args.siteName,
    }, opts);
}

/**
 * A collection of arguments for invoking getSite.
 */
export interface GetSiteArgs {
    /**
     * The site whose config should be retrieved.
     */
    siteName: string;
}

/**
 * A collection of values returned by getSite.
 */
export interface GetSiteResult {
    /**
     * The site config.
     */
    readonly config: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The site whose config should be retrieved.
     */
    readonly siteName: string;
}
/**
 * Retrieves the JSON pull-site info for a given site.  This can then be updated and sebsequently fed into the prismasdwan.Site resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prismasdwan from "@pulumi/prismasdwan";
 *
 * const site1 = prismasdwan.getSite({
 *     siteName: "Site1",
 * });
 * ```
 */
export function getSiteOutput(args: GetSiteOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSiteResult> {
    return pulumi.output(args).apply((a: any) => getSite(a, opts))
}

/**
 * A collection of arguments for invoking getSite.
 */
export interface GetSiteOutputArgs {
    /**
     * The site whose config should be retrieved.
     */
    siteName: pulumi.Input<string>;
}
